CREATE TABLE IF NOT EXISTS ads(
	id BIGINT NOT NULL AUTO_INCREMENT,
    provider_name VARCHAR(50) NOT NULL,
    provider_id VARCHAR(50) NOT NULL,
    provider_lead_url VARCHAR(200),
    status VARCHAR(200),
    brand VARCHAR(50),
    car_name VARCHAR(200),
    country VARCHAR(3),
    price DOUBLE,
    currency VARCHAR(3),
    mileage_km BIGINT,
    images JSON,
    year BIGINT,
    transmission VARCHAR(50),
    fuel VARCHAR(100),
    first_reg VARCHAR(50),
    color VARCHAR(50),
    engine VARCHAR(50),
    is_dealer SMALLINT,
    created_at TIMESTAMP,    
    active_at TIMESTAMP,
    PRIMARY KEY (`id`) USING BTREE,
    CONSTRAINT uniq_id_name UNIQUE (provider_id, provider_name),
    CONSTRAINT unique_url UNIQUE (provider_lead_url),
    INDEX USING BTREE (status),
    INDEX USING BTREE (created_at)
);
